// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcXXVsTWsj_QzSdlvRmo58Nd5J0NOZcR8',
    appId: '1:742072048759:web:01ae4f652bf9c41d203a72',
    messagingSenderId: '742072048759',
    projectId: 'chicstore-app',
    authDomain: 'chicstore-app.firebaseapp.com',
    storageBucket: 'chicstore-app.firebasestorage.app',
    measurementId: 'G-1RBCH1FMDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwSvLftm6YpJzPTCAWYdhjqXp8Adomm0o',
    appId: '1:742072048759:android:b3e5eeedb7838cd8203a72',
    messagingSenderId: '742072048759',
    projectId: 'chicstore-app',
    storageBucket: 'chicstore-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHOt4o6gVu8goQicmUm7cpCmeFWmx0CCs',
    appId: '1:742072048759:ios:b0a54d0af894d9b3203a72',
    messagingSenderId: '742072048759',
    projectId: 'chicstore-app',
    storageBucket: 'chicstore-app.firebasestorage.app',
    iosBundleId: 'com.example.chicstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHOt4o6gVu8goQicmUm7cpCmeFWmx0CCs',
    appId: '1:742072048759:ios:b0a54d0af894d9b3203a72',
    messagingSenderId: '742072048759',
    projectId: 'chicstore-app',
    storageBucket: 'chicstore-app.firebasestorage.app',
    iosBundleId: 'com.example.chicstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcXXVsTWsj_QzSdlvRmo58Nd5J0NOZcR8',
    appId: '1:742072048759:web:3cdf39d144382a32203a72',
    messagingSenderId: '742072048759',
    projectId: 'chicstore-app',
    authDomain: 'chicstore-app.firebaseapp.com',
    storageBucket: 'chicstore-app.firebasestorage.app',
    measurementId: 'G-QNCD6WK2B4',
  );
}
